### ISSUE TITLE
Callbacks plugin

### ISSUE THREAD

**Issue by mmoreram** [apisearch-io/search-server#77]
This plugin should allow the user to create callbacks before and after the middleware application per each command inside the project.

```
callbacks:
    -
        command: Query
        endpoint: http://localhost:9999
        method: GET
        bypass: true
        moment: before
```
